name: sonxemaycantho
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.24.2
  http: ^1.4.0  
  cupertino_icons: ^1.0.8
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.14.0
  firebase_storage: ^11.6.0
  google_sign_in: ^6.2.1
  crypto: ^3.0.6
  bcrypt: ^1.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0


flutter_native_splash:
  color: "#C54141"
  image: assets/logo/logo1.png
  branding: null
  android_gravity: center
  ios_content_mode: center
  fullscreen: true


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo1.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo/logo1.png"


flutter:

  uses-material-design: true
  assets:
    - assets/logo/logo1.png
    - assets/logo/gg.jpg

  fonts:
    - family: Itim
      fonts:
        - asset: assets/fonts/Itim-Regular.ttf