name: sonxemaycantho
description: "A new Flutter project."

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.30.0
  http: ^0.13.6  

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.13.1


flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/logo1.png"
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/logo/logo1.png"


flutter:

  uses-material-design: true
  assets:
    - assets/logo/logo1.png

  fonts:
    - family: Itim
      fonts:
        - asset: assets/fonts/Itim-Regular.ttf



