// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA0CG6EY9KALaZyfrBZrRyMUBRr2IvyKwc',
    appId: '1:501406586454:android:7b8602d5e3a900ce398df7',
    messagingSenderId: '501406586454',
    projectId: 'sonxemay-cantho',
    storageBucket: 'sonxemay-cantho.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDCQIPHSbXCh7WTY3zZPm1_sRwPLDYvKdk',
    appId: '1:501406586454:ios:036269950c81242d398df7',
    messagingSenderId: '501406586454',
    projectId: 'sonxemay-cantho',
    storageBucket: 'sonxemay-cantho.firebasestorage.app',
    iosBundleId: 'com.example.sonxemaycantho',
  );
}
